[package]
name = "xi-profile"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]

[dependencies]
chrono = "0.4"
sys-info = "*"
serde_json = "1.0"
xi-rpc = {version = "0.2", path = "./xi-editor/rust/rpc"}
